#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["src/backend/Api/Api.csproj", "src/backend/Api/"]
COPY ["src/backend/Database.Npgsql/Database.Npgsql.csproj", "src/backend/Database.Npgsql/"]
COPY ["src/backend/Infra.EntityFramework.Extensions/Infra.EntityFramework.Extensions.csproj", "src/backend/Infra.EntityFramework.Extensions/"]
COPY ["src/backend/Core/Core.csproj", "src/backend/Core/"]
COPY ["src/backend/Domain/Domain.csproj", "src/backend/Domain/"]
COPY ["src/backend/Application/Application.csproj", "src/backend/Application/"]
RUN dotnet restore "src/backend/Api/Api.csproj"
COPY . .
WORKDIR "/src/src/backend/Api"
RUN dotnet build "Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Api.dll"]